name: SmartTrashBinServer CI

on: push

jobs:
  test:
    env:
      MIX_ENV: test
    runs-on: ubuntu-latest
    services:
      postgres:
        image: binakot/postgresql-postgis-timescaledb
        ports: ['5432:5432']
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v2

      - name: Install Elixir
        uses: erlef/setup-elixir@v1
        with:
          otp-version: '24.2.2'
          elixir-version: '1.13.3'

      - name: Cache dependencies
        uses: actions/cache@v1
        with:
          path: deps
          key: ${{ runner.os }}-mix-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}
          restore-keys: |
            ${{ runner.os }}-mix-

      - name: Install Dependencies
        run: |
          mix deps.get

      - name: Cache build
        uses: actions/cache@v1
        with:
          path: _build
          key: ${{ runner.os }}-mix-build-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}
          restore-keys: |
            ${{ runner.os }}-mix-build-

      - name: Compile app
        run: MIX_ENV=test mix compile --warnings-as-errors

      - name: Run Tests
        run: |
          set +e
          mix test --trace

      - name: Check formatting
        run: mix format --check-formatted

      - name: Analyze code
        run: MIX_ENV=test mix credo --strict

      - name: Coveralls
        run: mix coveralls
  deploy:
    needs: test # Will only run if the test job succeeds
    if: github.ref == 'refs/heads/main' # Only run this job if it is on the main branch

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: main # Check out main instead of the latest commit
          fetch-depth: 0 # Checkout the whole branch

      - uses: actions/setup-python@v2
        with:
          python-version: 3.8.1

      - uses: mhanberg/gigalixir-action@v0.4.0
        with:
          GIGALIXIR_APP: tedious-cautious-tarantula
          GIGALIXIR_USERNAME: ${{ secrets.GIGALIXIR_USERNAME }}
          GIGALIXIR_PASSWORD: ${{ secrets.GIGALIXIR_PASSWORD }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
